### ISSUE TITLE
nextFailureCheck doesn't refresh on situation change.

### ISSUE THREAD

**Issue by Muddr** [severedsolo/UPFM#9]
There are times at which the `nextFailureCheck` is stuck at the +1800 when it should switch back to +10.

Some examples of this (I'm sure the are others):

- Using a plane.  It starts as `PRELAUNCH`, so after the first 10 seconds check, it sets the next check to +1800 making most plane flights safe for most of the flight.
- Going `SUB_ORBITAL` long enough for the 10 sec check will set the next check to +1800, making the re-entry safe from failures.

A quick and dirty debug fix as a proof of concept. 
```C#
private void CheckForFailures()
{
	if (!FlightGlobals.ready) return;
    if (KRASHWrapper.simulationActive()) return;
    if(FlightGlobals.ActiveVessel.FindPartModuleImplementing<ModuleUPFMEvents>() != null)
    {
        if(FlightGlobals.ActiveVessel.FindPartModuleImplementing<ModuleUPFMEvents>().tested == false) return;
    }

	//Muddr Start
	// If the last know situation isn't the same as the current reset nextFailureCheck
	// lastSituation defined at top of UPFMUtils class.
	if (lastSituation != FlightGlobals.ActiveVessel.situation)
	{
		Debug.Log("[Muddr - OhScrap](Situation Change) Was: " + lastSituation + " Now: " + FlightGlobals.ActiveVessel.situation);
		nextFailureCheck = Planetarium.GetUniversalTime() + 10;
	}

	lastSituation = FlightGlobals.ActiveVessel.situation;
	//Muddr End

	if (Planetarium.GetUniversalTime() < nextFailureCheck) return;
        <rest of code>
```

**Comment by severedsolo** [comment]
The prelaunch thing is supposed to be fixed with the last beta, I guess it didn't work for planes.

Suborbital, I'm aware of. It's a tricky one for a couple of reasons

1) reentry takes alot longer than launch, while ten second checks seem reasonable for a launch, on reentry the failure event is going to trigger alot more, simply because there's more of them. A potential solution for this would be to make 30 second checks if the craft switches from Suborbital to flying.

2) I really don't want your craft to become suddenly prone to failures because it entered Dunas atmosphere, or you decided to aerobrake. This one is easy, I'll just check if the vessel is at the home body before kicking in atmospheric checks.

**Comment by severedsolo** [comment]
Note to self: 
check if Vessel situation is PRELAUNCH after switching back to an in flight vessel. If not, we can just do if(ActiveVessel.Situation==VesselSituations. PRELAUNCH) return;

**Comment by severedsolo** [comment]
Github auto closed when I referenced it. Keeping open in case it's not fixed.

**Comment by severedsolo** [comment]
Fixed
